language: ruby
bundler_args: --without development system_tests
before_install:
  - rm Gemfile.lock || true
rvm:
  - 2.4

services:
  - docker

stages:
  - validation
  - test

jobs:
  include:
    - stage: validation
      script: bundle exec rake syntax
      script: bundle exec rake lint
    - stage: test
      script: bundle exec rake spec
      script: bundle exec rake beaker
