# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
require 'shellwords'

# ---- original file header ----
#
# @summary
#   Summarise what the function does here
#
Puppet::Functions.create_function(:'docker::docker_swarm_join_flags') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    
    opts = args[0] || {}
    flags = []

    if opts['join'].to_s != 'false'
      flags << 'join'
    end

    if opts['advertise_addr'].to_s != 'undef'
      flags << "--advertise-addr '#{opts['advertise_addr']}'"
    end
     
    if opts['listen_addr'].to_s != 'undef'
      flags << "--listen-addr '#{opts['listen_addr']}'"
    end
    
    if opts['token'].to_s != 'undef'
      flags << "--token '#{opts['token']}'"
    end

    flags.flatten.join(" ")
  
  end
end
