# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
require 'shellwords'

# ---- original file header ----
#
# @summary
#   Summarise what the function does here
#
Puppet::Functions.create_function(:'docker::docker_swarm_init_flags') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    
    opts = args[0] || {}
    flags = []

    if opts['init'].to_s != 'false'
      flags << 'init'
    end

    if opts['advertise_addr'].to_s != 'undef'
      flags << "--advertise-addr '#{opts['advertise_addr']}'"
    end
    
    if opts['autolock'].to_s != 'false'
      flags << '--autolock'
    end
    
    if opts['cert_expiry'].to_s != 'undef'
      flags << "--cert-expiry '#{opts['cert_expiry']}'"
    end
   
    if opts['dispatcher_heartbeat'].to_s != 'undef'
      flags << "--dispatcher-heartbeat '#{opts['dispatcher_heartbeat']}'"
    end  
     
    if opts['external_ca'].to_s != 'undef'
      flags << "--external-ca '#{opts['external_ca']}'"	    
    end

    if opts['force_new_cluster'].to_s != 'false'
      flags << '--force-new-cluster'
    end
    
    if opts['listen_addr'].to_s != 'undef'
      flags << "--listen-addr '#{opts['listen_addr']}'"
    end

    if opts['max_snapshots'].to_s != 'undef'
      flags << "--max-snapshots '#{opts['max_snapshots']}'"
    end     
    
    if opts['snapshot_interval'].to_s != 'undef'
      flags << "--snapshot-interval '#{opts['snapshot_interval']}'"
    end 
    
    flags.flatten.join(" ")
  
  end
end
