HOSTS:
  ubuntu-16-04:
    roles:
      - master
    platform: ubuntu-16.04-amd64
    hypervisor: docker
    image: ubuntu:16.04
    docker_preserve_image: true
    docker_command: '["/sbin/init"]'
    docker_image_commands:
      - 'apt-get install -y net-tools wget curl'
      - 'locale-gen en_US.UTF-8'

CONFIG:
  log_level: debug
  type: foss
